# Generated by Django 2.1.5 on 2019-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_count', models.DecimalField(decimal_places=2, max_digits=20)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
