# Generated by Django 2.1.5 on 2019-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_item', models.DateField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_income', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
